# Generated by Django 5.1.7 on 2025-03-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="description",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="workout",
            old_name="name",
            new_name="title",
        ),
    ]
